# Custom Language File for Launcher Customizer

[ejs.app]
title = "Lisopin Launcher"

[ejs.landing]
mediaGitHubURL = "#"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/b5d4qnuBpC"

[ejs.settings]
sourceGithubLink = "https://github.com/edsw0922/Lisopin_Launcher"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "리소핀 런처에 오신것을 환영합니다."
welcomeDescription = "Special thanks. SachilSir_Carrot, qaw_.85"
welcomeDescCTA = ""
